// Brand catalog - can be extended to fetch from database later
export const BRAND_CATALOG = [
  "STC",
  "Mobily",
  "ZAIN",
  "Atheer",
  "Cisco",
  "TBD",
  "Nutanix",
  "Contabo",
  "Docker",
  "SiteGround",
  "Vercal",
  "Dnet",
  "Nour",
  "3M",
  "Dell",
  "Lenovo",
  "Cloudflare",
  "WD",
  "FortiGate",
  "Dahua",
  "GE",
  "Arouba",
  "UTEC",
  "Autodesk",
  "Xerox",
  "PTC",
  "Microsoft",
  "Eplan",
  "MathWorks",
  "Adobe",
  "Dassault S",
  "Primapowe",
  "Salesforce",
  "CodeTwo",
  "Csiamerica",
  "3CX",
  "Envato",
  "Kuula",
  "Flimora",
  "SAP",
  "MindManag",
  "ManageEn",
  "Google",
  "Lucid",
  "Apple",
  "Samsung",
  "Synology",
  "HP",
  "ZKT",
  "CalssPro",
  "Owl Pro",
  "Vive",
  "IBS",
  "JIRA",
  "Illumio",
  "Veeam",
  "Kaspersky",
  "TwinGate",
  "WWG",
  "Raqueem",
]

export function searchBrands(query: string): string[] {
  if (!query) return BRAND_CATALOG
  const lowerQuery = query.toLowerCase()
  return BRAND_CATALOG.filter(brand => 
    brand.toLowerCase().includes(lowerQuery)
  )
}

